import { Language } from './types';
import { Camera, Upload, ScanLine, RotateCcw, CheckCircle, XCircle, HelpCircle, ChevronLeft } from 'lucide-react';

export const TRANSLATIONS = {
  [Language.ARABIC]: {
    appTitle: 'الماسح الضوئي الحلال',
    scanButton: 'مسح المكونات',
    uploadButton: 'تحميل صورة',
    cameraPermission: 'يرجى السماح بالوصول إلى الكاميرا',
    analyzing: 'جاري تحليل المكونات...',
    analyzingSub: 'قد يستغرق هذا بضع ثوانٍ',
    resultTitle: 'نتيجة المسح',
    backButton: 'مسح منتج آخر',
    statusHalal: 'حلال',
    statusHaram: 'حرام',
    statusMushbooh: 'مشكوك فيه',
    statusUnknown: 'غير معروف',
    overallSafe: 'هذا المنتج يبدو حلالاً',
    overallUnsafe: 'تحذير: يحتوي على مكونات حرام',
    overallDoubt: 'تحذير: يحتوي على مكونات مشكوك فيها',
    ingredientName: 'المكون',
    ingredientStatus: 'الحالة',
    ingredientReason: 'السبب',
    selectLanguage: 'اختر اللغة',
    errorTitle: 'حدث خطأ',
    errorMessage: 'لم نتمكن من معالجة الصورة. يرجى المحاولة مرة أخرى.',
    retry: 'أعد المحاولة',
  },
  [Language.ENGLISH]: {
    appTitle: 'Halal Scanner',
    scanButton: 'Scan Ingredients',
    uploadButton: 'Upload Photo',
    cameraPermission: 'Please allow camera access',
    analyzing: 'Analyzing ingredients...',
    analyzingSub: 'This might take a few seconds',
    resultTitle: 'Scan Result',
    backButton: 'Scan Another Product',
    statusHalal: 'Halal',
    statusHaram: 'Haram',
    statusMushbooh: 'Mushbooh',
    statusUnknown: 'Unknown',
    overallSafe: 'This product appears to be Halal',
    overallUnsafe: 'Warning: Contains Haram ingredients',
    overallDoubt: 'Warning: Contains doubtful ingredients',
    ingredientName: 'Ingredient',
    ingredientStatus: 'Status',
    ingredientReason: 'Reason',
    selectLanguage: 'Select Language',
    errorTitle: 'Error Occurred',
    errorMessage: 'Could not process the image. Please try again.',
    retry: 'Retry',
  },
  [Language.GERMAN]: {
    appTitle: 'Halal Scanner',
    scanButton: 'Zutaten scannen',
    uploadButton: 'Foto hochladen',
    cameraPermission: 'Bitte erlauben Sie den Kamerazugriff',
    analyzing: 'Zutaten werden analysiert...',
    analyzingSub: 'Dies kann einige Sekunden dauern',
    resultTitle: 'Scan-Ergebnis',
    backButton: 'Ein anderes Produkt scannen',
    statusHalal: 'Halal',
    statusHaram: 'Haram',
    statusMushbooh: 'Meschbuh', // Often used German transliteration or just Mushbooh
    statusUnknown: 'Unbekannt',
    overallSafe: 'Dieses Produkt scheint Halal zu sein',
    overallUnsafe: 'Warnung: Enthält Haram-Zutaten',
    overallDoubt: 'Warnung: Enthält zweifelhafte Zutaten',
    ingredientName: 'Zutat',
    ingredientStatus: 'Status',
    ingredientReason: 'Grund',
    selectLanguage: 'Sprache wählen',
    errorTitle: 'Fehler aufgetreten',
    errorMessage: 'Das Bild konnte nicht verarbeitet werden. Bitte versuchen Sie es erneut.',
    retry: 'Erneuter Versuch',
  },
};

export const ICONS = {
  Camera,
  Upload,
  ScanLine,
  RotateCcw,
  CheckCircle,
  XCircle,
  HelpCircle,
  ChevronLeft
};
